### ISSUE TITLE
Update docker images to latest version of api-inference-community version

### ISSUE THREAD

**Issue by StephenHodgson** [huggingface/api-inference-community#328] opened 2023-08-23 17:35 UTC
some images are out of date and require updates to get hugging face hub to work correctly with audio endpoints

**Comment by osanseviero** [comment] 2023-08-23 21:45
This seems like a duplicate of #326 . Let's keep discussion in that thread

**Closed by osanseviero** 2023-08-23 21:45 UTC

**Comment by StephenHodgson** [comment] 2023-08-25 16:24
I'm just frustrated that the issue was closed before the discussion was complete.
